bike = ["jawa", "benneli", "bullet", "bmw", "husqverna", "harley"]
value = [2,1.5,1,10,3,20]
print(bike)
print(value)
bike.append("tvs")
print("append",bike)
bike.extend(["bajaj","honda"])
print("extend",bike)
bike.insert(1,"triumph")
print("insert",bike)
bike.remove("tvs")
print("remove",bike)
bike.pop()
print("pop",bike)
print(bike.index("bmw"))
print(bike.count("tvs"))
print(bike.count("jawa"))
bike.reverse()
value.reverse()
print("reverse",bike,value)
bike.sort()
value.sort()
print("sort",bike,value)
bikes= bike.copy()
print("copy list",bikes)
bike.clear()
value.clear()
print("clear list",bike,value)