print("Roses are {color}")
print("{plural noun} are blue")
print("I love {name}")
color = input("Enter a color")
pl_noun = input("Enter a plural noun")
name = input("Enter a name")
print("Roses are ",color)
print(pl_noun," are blue")
print("I love ", name)